### ISSUE TITLE
Unable to complete installation on fresh Ubuntu 16.04 install

### ISSUE THREAD

**Issue by jeremycfd** [ucscGenomeBrowser/kent#1]
Hello,

I've been trying for a couple of days now to get these applications running on a new machine with a fresh installation of Ubuntu 16.04. I have followed the instructions in the readme, but when I attempt to make any of the individual applications (for instance, fixCr, as suggested in the readme), I get the following error:

```
~/Installs/kent/src/utils/fixCr$ sudo make
gcc -O -g -o /home/jc/bin/x86_64/fixCr fixCr.o    ../../lib/x86_64/jkweb.a -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl -lstdc++ -lrt -lm ../../htslib/libhts.a -pthread -L/lib -lssl -lcrypto -lpng12 -lm
gcc: error: ../../htslib/libhts.a: No such file or directory
../../inc/userApp.mk:31: recipe for target '/home/jc/bin/x86_64/fixCr' failed
make: *** [/home/jc/bin/x86_64/fixCr] Error 1
```

I was able to resolve this error by going to the htslib directory and doing make. The readme did not indicate that I needed to do that, so I'm wondering if that was an oversight or if this is an indication that the makes I did in previous parts of the readme somehow failed without alerting me. They did give a couple of warnings, but they didn't seem to outright fail, as far as I could tell.

However, I now receive the following error when trying to proceed:

```
~/Installs/kent/src/utils/fixCr$ sudo make
gcc -O -g  -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -DUSE_SSL   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I../../htslib -I/include -I/usr/include/libpng12  -o fixCr.o -c fixCr.c
gcc -O -g -o /home/jc/bin/x86_64/fixCr fixCr.o    ../../lib/x86_64/jkweb.a -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl -lstdc++ -lrt -lm ../../htslib/libhts.a -pthread -L/lib -lssl -lcrypto -lpng12 -lm
/usr/bin/ld: cannot open output file /home/jc/bin/x86_64/fixCr: No such file or directory
collect2: error: ld returned 1 exit status
../../inc/userApp.mk:31: recipe for target '/home/jc/bin/x86_64/fixCr' failed
make: *** [/home/jc/bin/x86_64/fixCr] Error 1
```

I have verified that /bin/x86_64 is in my path, so I'm a bit lost as to what's going on here... Please let me know if you have any suggestions. I would be happy to append files of the output from all of these makes if that would help.

Best,
Jeremy

**Comment by christopherLee1** [comment]
Hi Jeremy,

Thank you for your question about installing the kent source on Ubuntu. Are you trying to install a full mirror or just particular utilities? If you are only interested in the individual utilities, you can find pre-compiled binaries here, just select the linux.x86_64 directory and download whichever programs you want:
http://hgdownload.soe.ucsc.edu/admin/exe/

If instead you want all the pre-compiled utils, navigate to the directory on your machine where you want the apps installed and run the following rsync command:
`rsync -aP rsync://hgdownload.cse.ucsc.edu/genome/admin/exe/linux.x86_64/ ./`

Lastly, if you are instead looking to install a full Genome Browser mirror, we can help you further if you post your message to our public genome-mirror mailing list:
genome-mirror@soe.ucsc.edu

Christopher Lee
UCSC Genomics Institute
