### ISSUE TITLE
faSplit produces thousands of files

### ISSUE THREAD

**Issue by KristinaGagalova** [ucscGenomeBrowser/kent#15]
Hi, 
I am trying to split a large fasta file containing a genome assembly. The command I am using is:
```
faSplit sequence myGenome.fa 20 myGenome_
``` 
The command produces thousands of files. The file is quite large, 32G, so I believe there there is something related to that

**Comment by galt** [comment]
For help, please use the genome browser help list.
genome-www@soe.ucsc.edu
This is a public forum where people can see and search for answers.

To get private help, you can write to:
genome-www@soe.ucsc.edu

**Comment by galt** [comment]
Oops, the public forum is here: (without -www)
genome@soe.ucsc.edu
