### ISSUE TITLE
Account creation error on Ubuntu0.16.04.1 with mysql 5.7.16

### ISSUE THREAD

**Issue by spooknick** [ucscGenomeBrowser/kent#2]
Hi
The default settings of mysql `Server version: 5.7.16-0ubuntu0.16.04.1 (Ubuntu)` prevents account creation, it returns an sql error.

> Warning/Error(s):
Can't start query:
INSERT INTO gbMembers SET userName='testtt',realName='testtt',password=':B:s576OmtG:abbe74926fe1b60e70454d09ee444415',email='whatever@gmail.com', lastUse=NOW(),accountActivated='Y'
mySQL error 1364: Field 'newPassword' doesn't have a default value (profile=<noProfile>, host=localhost, db=hgcentral)

The problem comes from the `sql_mode` default value which is:

`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION `

Editing `/etc/mysql/my.cnf` by adding

`[mysqld]
sql_mode =`

Solved the issue.

**Comment by christopherLee1** [comment]
Hi Spooknick,

Thanks for reporting this error about account creation on Ubuntu 16. We are confused as to how you generated this error, are you experiencing this issue while running the GBiB, installing a mirror manually, or using the mirror install script? We may have to fix separate things depending on how the error was produced.

Additionally, we can further help with your mirror installation if you send your questions to genome-mirror@soe.ucsc.edu. This way your questions are posted to a Google Group that others can subscribe to and search for related questions. For example, I was able to find some questions related to sql_mode and how it is likely related to the MySQL version:
https://groups.google.com/a/soe.ucsc.edu/forum/#!searchin/genome-mirror/sql_mode%7Csort:date

Thanks again for finding this error!

Christopher Lee
UCSC Genomics Institute
