### ISSUE TITLE
source code download site is down

### ISSUE THREAD

**Issue by byb121** [ucscGenomeBrowser/kent#21]
Hi,

It seems this site is down: https://users.soe.ucsc.edu/~kent/src/

I'm after blatSrc35.zip, which seems only available there.

Thanks,

**Comment by maximilianh** [comment]
The new site is https://hgwdev.gi.ucsc.edu/~kent/src/

Can you tell us where you found the old link?

**Comment by maximilianh** [comment]
Here is one outdated link:
http://genome.ucsc.edu/goldenpath/help/hgTracksHelp.html

**Comment by byb121** [comment]
yes, that's where I found the link.

**Comment by byb121** [comment]
The page as well: http://hgdownload.soe.ucsc.edu/downloads.html#source_downloads
