### ISSUE TITLE
Issue with fixCr

### ISSUE THREAD

**Issue by ashlingcha** [ucscGenomeBrowser/kent#24]
Hi there,
when I try to make fixCr, fixCr.o is made but not gotCr.c
this is the output: 
`/bin/sh: mysql_config: command not found
/bin/sh: mysql_config: command not found
gcc -O -g  -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I../../htslib -I/include -I/usr/include/libpng16  -o fixCr.o -c fixCr.c
gcc -O -g -o /home/ashling_charles/bin/x86_64/fixCr fixCr.o    ../../lib/x86_64/jkweb.a "-L/usr/lib64 -lmysqlclient" -lstdc++ -lrt -lpthread -lssl -lcrypto ../../htslib/libhts.a -L/usr/lib64 -lpng16 -lm -lz 
true /home/ashling_charles/bin/x86_64/fixCr`

I know without this hal wont work. 
Thanks in advance.

**Comment by ashlingcha** [comment]
It may have to do with this part of the instructions: 'rehash' if necessary so your shell can find the fixcr program in ~/bin/$(MACHTYPE).
May be a silly question but what is $(MACHTYPE) in this context?

**Comment by maximilianh** [comment]
MACHTYPE is explained in the main README file.

Instead of building the tools yourself, don't you prefer to download them
precompiled, from  http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/ ?

**Comment by ashlingcha** [comment]
The link you sent me looks like they're for the lastz alignment tools, whereas I'm trying to compile the haltools which requires kent. (https://github.com/ComparativeGenomicsToolkit/hal) I don't mind getting them precompiled I just need to get the tools.
thanks

**Comment by maximilianh** [comment]
Oh! Don’t the haltools mention how to build the kent tools ? There is no
need to set machtype anymore. What does the haltools docs say what you
should do?

**Comment by ashlingcha** [comment]
haltools only mentions that I should be pointing to the kentsrc tree - I had it working before but for some reason I had to reinstall kent and ever since I've had troubles compiling it 
These are the instructions:
`module load hdf5
cd $MYGROUP
git clone https://github.com/ucscGenomeBrowser/kent.git
cd kent (compile the packages as required)

cd $MYGROUP
git clone https://github.com/ComparativeGenomicsToolkit/hal.git

export  ENABLE_UDC=1
export KENTSRC=$MYGROUP/kent/src (i've cloned kent in my group directory)
git clone https://github.com/benedictpaten/sonLib.git
pushd sonLib && make && popd

cd hal
make`

**Comment by ashlingcha** [comment]
I tried to make a directory called kent and put all the prebuilt tools in there via  http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/ but that didn't work

**Comment by maximilianh** [comment]
@glennhickey any suggestions ?

**Comment by maximilianh** [comment]
Yes you’ll need to build the Kent source tree . Glenn will have an idea why
or which parts. Does a simple “cd kent/src; make -j8” not work for you?

**Comment by glennhickey** [comment]
HAL's build only depends on the Kent source tree when the `ENABLE_UDC` [environment variable is set.](https://github.com/ComparativeGenomicsToolkit/hal/blob/master/include.mk#L96-L106).  

Unless you are building HAL in order to link it to a custom build of the UCSC genome browser which you want to use as a back-end for visualizing snake tracks, then there is no reason a I can think of to build it this way.  This is touched on a bit in HAL's [README](https://github.com/ComparativeGenomicsToolkit/hal).

@ashlingcha Are you trying to build the genome browser along with hal?  Where do the instructions which you posted that include `export  ENABLE_UDC=1` come from?

**Comment by ashlingcha** [comment]
I'm trying to just build hal. Those instructions were given to me by the pawsey helpdesk, and have worked before but I can't get it to run this time.

**Comment by maximilianh** [comment]
You don't need the UCSC kent tree to build HAL.

**Comment by ashlingcha** [comment]
Thanks, I've gotten hal to work without kent now - unsure why I was advised to install it this way. Thanks for your help.
