### ISSUE TITLE
Patch to build with current htslib

### ISSUE THREAD

**Issue by tillea** [ucscGenomeBrowser/kent#26]
Hi,
I'd like to continue the discussion from issue #13 in a new issue.  I spent some more time on the idea of packaging a part of the code in the kent repository (for licensing questions I'll open a new thread) for Debian.  Together with John Marshall from htslib upstream I developed a [patch](https://salsa.debian.org/med-team/libucsc/blob/master/debian/patches/use_debian_packaged_htslib.patch) which enables building blat and isPcr sucessfully with the Debian packaged htslib (currently version 1.10.2).
Feel free to take over this patch in your code.
Kind regards, Andreas.

**Comment by braneyboo** [comment]
Thanks for this.   We'll take a look.

**Comment by braneyboo** [comment]
I created an internal ticket for this.     I don't know when we'll get to it.
