### ISSUE TITLE
Missing license for font mgSixhi6.c

### ISSUE THREAD

**Issue by tillea** [ucscGenomeBrowser/kent#27]
Hi,
since I intend to package parts of your code I was checking single licenses of files.  I've found for most of the fonts you are adding

    Copyright: 1984-1989, 1994 Adobe Systems Incorporated.,
               1988, 1994 Digital Equipment Corporation.
    License: Adobe

and for the file src/lib/font/mgSail8.c I've found

    Copyright: 2011 LatinoType Limitada <luciano@latinotype.com>
    License: SILOpenFontLicense

but for the file src/lib/font/mgSixhi6.c I failed to find any license statement.  At least for Debian this would be a killer feature since no license means non-distributable.  May be you know where this file is from and it would be great if you could add this to your documentation.
Kind regards, Andreas.

**Comment by braneyboo** [comment]
Hmmm..... I'll get back to you.

**Comment by braneyboo** [comment]
Our research indicates that this font is licensed under the BSD license as it was part of Autodesk Animator which was released with that license.

https://en.wikipedia.org/wiki/Autodesk_Animator
