### ISSUE TITLE
Consistent documentation for kent tools

### ISSUE THREAD

**Issue by raivivek** [ucscGenomeBrowser/kent#28]
Hi, I was wondering if it's possible to adopt a consistent documentation scheme for kent tools as found here -- http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/FOOTER

The reason I'm making this request because Bioconda recipe script parses this document to automatically create packages for distributing the tools. However, inconsistency requires case-by-case parsing of specific programs making maintainability non-trivial.

Few examples,

1. Some tools have the following comment string missing
```### kent source version 394 ###```
1. Some tools have no description -- an example with no description
	```
	================================================================
	========   bedJoinTabOffset   ====================================
	================================================================
	usage:
	   bedJoinTabOffset inTabFile inBedFile outBedFile
	```
1. Some have unexplained comments
	```
	================================================================
	========   bedPartition   ====================================
	================================================================
	### kent source version 394 ###
	Error: wrong # args
	```

If there's an alternative way to obtain these descriptions, let me know. I'm happy to help as well. Thanks!

**Comment by maximilianh** [comment]
Hi Vivek, can you tell us what you are doing for bioconda that requires
descriptions for all our tools?

>

**Comment by raivivek** [comment]
Hi @maximilianh Bioconda creates a single package for each tool. For this, it parses this documentation file. Here's where it happens -- https://github.com/bioconda/bioconda-recipes/tree/master/scripts/ucsc

> The script `create-ucsc-packages.py` downloads the program listing from UCSC, downloads the source code, and creates recipes for every identified program (e.g., 115 programs in v324). There are some special cases handled by the script. The script uses the templates in this directory to be able to compile the tools individually in each recipe.

The consistent documentation will minimize "special case handling" as new tools are added making version updates easier.

**Comment by braneyboo** [comment]
Hey @raivivek ,

Thanks for pointing this out.

I'll get this fixed for our next release of the tools which will be v395 on March 17.

**Comment by raivivek** [comment]
Thanks @braneyboo! Appreciate it.

**Comment by raivivek** [comment]
@braneyboo Thanks for the changes so far. Really appreciate it. There's a few oddities in the document still, so just wanted to make sure it's somewhere on your agenda. For example, `ucscApiClient` `chromToUcsc` etc.

**Comment by braneyboo** [comment]
Hey @raivivek , thanks for the prod.   We have a long list of things to do and sometimes it takes a reminder to get us going.

**Comment by maximilianh** [comment]
I think we can close this. The problems were fixed last year and I think the ticket was accidentally re-opened. @raivivek let us now if you can still see problems, but the current FOOTER.txt looks fine to me.

Also, we are thinking about a version of the source repo where the non-MIT-license parts are removed. Let me know if this would help with the bioconda integration in some way.
