### ISSUE TITLE
Error compiling Source Tree

### ISSUE THREAD

**Issue by stefandiederich** [ucscGenomeBrowser/kent#3]
Dear all,

i want to use the BigWig functionality in ensembles VEP software and therefore I need to install Bio::DB::BigFile and this requires the compiled jkweb.a library from Jim Kent's source tree. 

I am following your README to compile and always get the error that openssl/sha.h could not be found. 

`
udc.c:39:25: fatal error: openssl/sha.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
../inc/common.mk:419: die Regel für Ziel „udc.o“ scheiterte
make: *** [udc.o] Fehler 1
administrator@k-hg-srv1:/media/Berechnungen/newVEP/kent-335_base/kent-335_base/src/lib$ make > make.err
udc.c:39:25: fatal error: openssl/sha.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
make: *** [udc.o] Fehler 1
`

Can you please tell me what I am doing wrong and what I can do to solve this issue.

Thanks for your help in advance. 
Stefan

**Comment by christopherLee1** [comment]
Hi Stefan,

Thank you for reporting this, you have indeed found a bug in our source code. Can you please try installing openssl on your machine and then rerunning the make?

We will fix this bug soon, thanks again for finding it!

Christopher Lee
UCSC Genomics Institute

**Comment by maximilianh** [comment]
Closing this, the missing IFDEF was added two weeks ago.
