### ISSUE TITLE
Question regarding bedToBigBed versioning 

### ISSUE THREAD

**Issue by bonitalam** [ucscGenomeBrowser/kent#30]
The ENCODE project is trying to register various versions of bedToBigBed used by different pipelines, and I'm having trouble understanding the different versioning conventions used. We have a 2.6, 2.7, 369, and 377 version currently. As you can see here: https://www.encodeproject.org/software/bedToBigBed/

It seems like bedToBigBed was updated to 2.7 some time in 2015: https://github.com/ucscGenomeBrowser/kent/commit/9febf81c75ac0b2b2fb5bc6d820971720d9eb96c#diff-f45d1e877202ab7a14ff9561296e0d87

If those who are stating they are using the bedToBigBed v. 2.7 - can we point to this http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64.v369/ which was released in 2018? Or one of the official GitHub releases? I would just like to know what is the best way to refer/link to bedToBigBed v. 2.7 through a repo or official download. 

Thank you for your help!

**Comment by braneyboo** [comment]
Hey @bonitalam ,

Your question has made me realize that we've had a few bug fixes without incrementing our release numbers.    I think you want at least 2.7.    The other release numbers are the release numbers of our whole code base.

Ideally you'd be pointing people to http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/ which is our latest version.    

In response to your email I'm going to go to 2.8 for bedToBigBed and add this version number to wigToBigWig and bedGraphToBigWig as well.   This will go out to our public site in about a month.

I hope this answers your question.   Let me know if you want more detail.

brian

**Comment by bonitalam** [comment]
Hi Brian! Thank you for the response. Is that version you linked (http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/) v395? I just want to confirm. Will this current version be archived here, once you release the next version out to the public:

http://hgdownload.soe.ucsc.edu/admin/exe/

I see there are archived links for v369 and v385. We should want to point people to versions that we know are stable and perhaps can provide at least a download checksum.

**Comment by braneyboo** [comment]
Hmmm... we don't provide archives for binaries except for a little while after we upgrade our OS for the builds.   Those directories will disappear after a while (supposedly ;-).

I like the idea of y'all recommending a particular binary that doesn't change, but I think you'll have to host it yourself.
