### ISSUE TITLE
Additional space in the RepeatMasker *.out header

### ISSUE THREAD

**Issue by SergejN** [ucscGenomeBrowser/kent#31]
Dear UCSC team,

While working with the repeat annotation for the axolotl genome, I found a small bug in hgLoadOut. Sometimes the SW score is so large that RepeatMasker introduces an additional space into the header. Then the condition "if (!startsWith("   SW   perc perc", line))" at https://github.com/ucscGenomeBrowser/kent/blob/022eb4f62a0af16526ca1bebcd9e68bd456265dc/src/hg/makeDb/hgLoadOut/hgLoadOut.c#L189 fails. 

Best,
Sergej

**Comment by braneyboo** [comment]
Thanks for reporting this @SergejN .   Could you maybe attach a small file that demonstrates this problem?    I'll look into this shortly.

**Comment by SergejN** [comment]
Hi @braneyboo , 
I'm sorry, I completely overlooked your response!

I attach a fragment of the file that causes hgLoadOut to fail.

```
hgLoadOut -tabFile=dummy -nosplit test LTR.RM.out
LTR.RM.out doesn't seem to be a RepeatMasker .out file, first line seen:
    SW   perc perc perc  query                 position in query           matching                 repeat                             position in repeat
```
my guess is that a large number, e.g. in line 36, 48, 59, 80 and so on), causes the overall column alignment to shift one base to the right, thus, introducing an additional space. If you remove the extra space in the header line, then everything works fine.
[problem.out.txt](https://github.com/ucscGenomeBrowser/kent/files/4371982/problem.out.txt)

Best,
Sergej

**Comment by braneyboo** [comment]
Awesome, thanks @SergejN .   I'm on SPRING BREAK at the moment, but I'll get back to you before the end of the week.

**Comment by braneyboo** [comment]
Fixed this by adding yet another special case to recognize the first line of a *.out file.

Thanks for reporting it @SergejN.
