### ISSUE TITLE
Please support COVID-19 BioHackathon and choose a free license for parts of your code to build blat

### ISSUE THREAD

**Issue by tillea** [ucscGenomeBrowser/kent#32]
Hi,
we had some past discussion about the licensing of the complete code of this repository.  I've understood that you did not consider this.  However, parts of the libraries are featuring an MIT license and I would like you to consider to change the license of only those parts that might enable us to package blat for Debian.  Debian is currently joing the COVID-19 Biohackathon and when doing so we intend to package everything that could contribute to fight this disease.  We would greatly appreciate your contribution to this fight.
I have extracted the following code parts as beeing necessary to successfully build blat under Debian:

    src/blat/*
    src/jkOwnLib/*

The other directories that are needed for building are MIT licensed.  Once you are at it for other projects we could also use

    src/isPcr/*

While this is of lower importance as blat it would be great to choose MIT or whatever free license you might decide for.
I would really appreciate your decision to change the license of this part of your code and the Debian community would be thankful for this contribution.
Kind regards
        Andreas.

**Comment by AnnZweig** [comment]
The usage you propose is considered "personal use," as long as any product that arises from such use is not for commercial gain.  In that case, you would need to contact Jim Kent at
Kent Informatics, the owner of the copyright.  He and we are happy to contribute to anything you may do to combat coronavirus.
