### ISSUE TITLE
mafToPsl out of range 

### ISSUE THREAD

**Issue by kingralph80** [ucscGenomeBrowser/kent#34]
Hi,

I used the current version (github) from mafToPsl of convert a maf file generated by GSAlign to psl. However, the tool ended with the error: 
"Coordinates out of range line 103592 of B73v5.CML322.50.200.maf"

I will post the line that causes the error (103592) plus the line prior in the next message but I think mafToPSL is maybe incorrect as maf is 1 based. The line that causes the issue starts with:
s qry.chr1 304926865 658 + 304927522

If you add 304926865 (Start) + 658 (Alignment) -1 (1based) = 304927522, this is the exact end of  the source length of 304927522. Is a possible that mafToPsl is off by 1 bp (0 based)?

**Comment by kingralph80** [comment]
The full alignment that causes the error in the maf file:

a score=645
s ref.chr1 308444775 654 + 308452471 gtgttcatggtttcggttttgggtctcgggATTTAGGATTTAAGGGTTTGGGGTTTAGTGTGATGTAGCTCAAGGGATGATAAAAACAACCTTACTTATTTCAGTAGCCAAAACATGGGCGGTGG----GTGGGAGGCATGAAATTGTTGTTCAATGACGAAAACATGTGTCACGGGAGGCCAAAAATAGACTTGCAGGCCTCCGGGAACCAAAACGTGTACTATGGTTTGAACACTTATGTACTATGGTTGGACACTAAATTGGTTGTTCTACCATGAAAACATGTGTTGTAGCTCACGCGAGGCCAAAAACAACCTTACCAGTCTTAGTGGCCAAAACATGGGTGGCGGACGGGAGGCATGAAATCGTTGTTCAACGACGAAAACATGTGTCGCGGGAGGCCAAAAATAGTCTTACCGACCTCCGGGGACCAAAACGTGTACTATGGTTTGGAGACTCAAGTAATCTTCTATTATGGTTTGGTCATTAAAATCTtttagtgttggtgtttagggttatggtttcaggtgtaggTttattgattagggtttggggttcggggcttagggtttagggtttggggtttggggttaagggttcgggtgtggggttcatggttttGggtttggggctcatggtttagggtttaggattTTG
s qry.chr1 304926865 658 + 304927522 gtgttcatggtttcggttttgggtctcggggtttaggatttaagggtttggggtttAGTGTGATGTAGCTCAAGGGATGATAAAAACAACCTTACTTATTTCAGTAGCCAAAACATGGGCGGTGGGCGCGCGGGAGGCATGAAATTGTTGTTCAATGACGAAAACATGTGTCACGGGAGGCCAAAAATAGACTTGCAGGCCTCCGGGAACCAAAACATGTACTATGGTTTGAACACTTATGTACTATGGTTGGACACTAAATTGGTTGTTCTACCATGAAAACGTGTGTTGTAGCTCACGCGAGGCCAAAAACAACCTTACCAGTCTTAGTGGCCAAAACATGGGTGGGGGACGGGAGGCATGAAATCGTTGTTCGACGACGAAAACATGTGTAGCGGGAGGCCAAAAATAGTCTTACCGACCTCCGGGGACCAAAACGTGTACTATGGTTTGGAGACTCAAGTAATCTTCTATTATGGTTTGGTCATTAAAATCTtttagtgttggtgtttagggttatggtttcaggtgtaggattattgattagggtttggggttcggggcttagggtttagggtttggggtttggggttaagggttcgggtgtggggttcatggtttttggtttggggctcatggtttagggtttaggattTTG

**Comment by braneyboo** [comment]
Thanks for reporting this, I'll get back to you soon.

**Comment by kingralph80** [comment]
Thanks,
this is actually very confusing. The author for GSAlign stated that MAF format is 1-based, but on the UCSC definition for the format, I only see 0-based for the start position. Very confusing.

**Comment by maximilianh** [comment]
Hi, I am curious: is there a particular reason why you use GSAlign? This is
an unusual choice for an aligner....

**Comment by kingralph80** [comment]
Hi, yes I know we are using very large genomes (maize 2.4 Gb) with a large degree of structural variation. So we tested a number of different genome alignment strategies including:
The UCSC intra and interspecific pipelines, progressive cactus, minimap, ATAC and GSAlgin. With GSAlign we get the larges alignment with still very high ASI, but at a blazing speed. 
A pairwise alignment of two maize genomes e.g. took more than a week with pr. cactus at 40 threads but only 1-1.5h with GSAlign ones the indexing is done. 
In the GSAlign paper they also compare to mumer 4 so we did not test that but it seems to be the quickest solution and supports soft repeat-mapping .  Unfortunately, while maf-convert can convert the output mafToPsl cannot, and that is very concerning to us. So it makes sense to figure this out before we invest all the time aligning all genomes.

**Comment by kingralph80** [comment]
Please let me know if you know an alternative aligner for large genomes to compare diverse genomes.

**Comment by maximilianh** [comment]
Sorry, one more question: is your goal to get a whole-genome alignment of
several plant genomes that you can show in the UCSC Genome Browser?

What do you mean with "UCSC intra and interspecific pipelines" - is this
our lastz/chains/net pipeline? In this case, I imagine the slow step is
lastz. Have you tried to optimize the lastz parameters? If not, I imagine
the lastz author may have some good ideas on how to speed it up.

**Comment by kingralph80** [comment]
to your second question: yes those steps include lastz. 

1.) The goal is a pairwise alignment between diverse ecotypes to a single reference. We are mapping TF binding sites in F1 hybrids. To avoid mapping bias, we are mapping against a diploid genome with chrom. from both parents. Hence we need the chain file between both parents to uplift the variants VCF from reference to the diverse parent. We essentially need the chain to compare genome regions to find allelic bias.

**Comment by maximilianh** [comment]
So your goal is not "to get a whole-genome alignment of several plant
genomes that you can show in the UCSC Genome Browser". You need a liftOver
chain file.

Why are you not using lastz, which is the normal aligner for chain files?
If you found it to be too slow, have you tried to optimize the lastz
parameters? The parameters, seed length and match pattern, make all the
difference. Its author could probably help.

I have not heard of GSAlign being used for building chain files. It looks
like an NGS read aligner.

**Comment by maximilianh** [comment]
One of my colleagues just commented that I was wrong: almost-identical genomes we don't align with lastz. We use BLAT and that would work for your organisms. Have you tried our doSameSpeciesLiftOver pipeline? http://genomewiki.ucsc.edu/index.php/DoSameSpeciesLiftOver.pl

**Comment by kingralph80** [comment]
Hi, yes we have tried that doSameSpeciesLiftOver. However, our genomes even though they are all maize, are not very similar. Maize is among the most diverse lines and with cactus or doSameSpeciesLiftOver we can only align ~50%. one average we have about 10 million homoz. SNPs between lines but what is so critical is the structural variation, INDELs and translocation is very high compared to humans for example. 
GSAlign was just published less than two months ago, and it does use the BWT index but is otherwise very similar to "minimap2" and similar tools. You are right to try the other tools and we are currently run doSameSpeciesLiftOver as a comparison but so far it looks like the alignment length and ASI look better for GSAlign. Again we are no expert and I really appreciate the feedback.

**Comment by kingralph80** [comment]
Btw to the original problem the author of GSAlign responded and will change the maf to a zero-based system. I think that MAF should be zero-based at least if I understand the definition correctly.

**Comment by braneyboo** [comment]
You're right, @kingralph80 , that MAF is 0-based.

**Comment by yuzhenpeng** [comment]
hello, I met the same problem with you used lastz.
I want to know how to solve it (MAF Coordinates error).
thank you.
![image](https://user-images.githubusercontent.com/31943277/85941959-d2049e00-b958-11ea-9408-e748034f649f.png)

@kingralph80  @braneyboo

**Comment by CarpeVida** [comment]
Thanks for reporting that issue. We cannot fully diagnose the problem given only the information you provided. It looks like there may be an issue with the input file 'out.maf' but it is hard to say without knowing how out.maf was generated. It also appears strange that the strand is not "+" or "-" but "?" instead. This may indicate some earlier file or process is causing an error. Could you please provide more information on your entire pipeline and objectives of these commands?

Please know you can write questions to our public mailing-list either at genome@ucsc.edu or directly to our internal private list at genome-www@soe.ucsc.edu.

Daniel Schmelter
UCSC Genome Browser
