### ISSUE TITLE
pngwrite.c:7:87: fatal error: png.h: No such file or directory

### ISSUE THREAD

**Issue by boomler** [ucscGenomeBrowser/kent#4]
when I go to `./src/lib` and type `make` :

`
genemind1@iZuf636tvvpjh8fy0ety3pZ:~/kent/src/lib$ make
/bin/sh: 1: libpng-config: not found

/bin/sh: 1: libpng-config: not found

/bin/sh: 1: mysql_config: not found

/bin/sh: 1: mysql_config: not found

gcc -O -g  -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_ucscKent   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I../htslib -I/include   -o pngwrite.o -c pngwrite.c
pngwrite.c:7:87: fatal error: png.h: No such file or directory
 #include "png.h"   // MUST come before common.h, due to setjmp checking  in pngconf.h
                                                                                       ^
compilation terminated.
make: *** [pngwrite.o] Error 1
`

**Comment by christopherLee1** [comment]
Hi boomler, do you have the following dependencies installed?
http://genome.ucsc.edu/goldenPath/help/mirrorManual.html#software-requirements

**Comment by pkerpedjiev** [comment]
You need the `libpng-dev` package:

In Ubuntu:

```
sudo apt-get install libpng-dev
```
