### ISSUE TITLE
Gene tracks (UCSC Genes & NCBI RefSeq) show aminoacid sequence as generated from the genome, not from the actual transcript CDS.

### ISSUE THREAD

**Issue by ifokkema** [ucscGenomeBrowser/kent#40]
Hi there,

As part of a project between [LOVD](https://github.com/LOVDnl/LOVD3) and [VariantValidator](https://github.com/openvar/variantValidator), I've been reviewing transcript mappings of transcripts where mismatches occur between the genome and the transcript sequence. Of course, these are hard to map to the genome, and different tools use different methods for this mapping. I was using the UCSC genome browser's mapping to verify results but I noticed sometimes the amino acids reported in the gene tracks do not actually match the transcript's CDS, but instead, seem to be translations from the genome sequence.

Some examples:
NM_015120.4 (NCBI RefSeq status: Reviewed)
[`NC_000002.11:g.73677655A>G`](https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chr2%3A73677650-73677660)
Both gene tracks map this variant to `NM_015120.4:c.3998A>G` / `p.(Tyr1333Cys)`, but position 1333 of the CDS of NM_015120.4 does not contain a Tyr (Y), it contains a Thr (T).
Variant Validator maps this variant to `NM_015120.4:c.4004A>G` / `p.(Tyr1335Cys)`, which does match the CDS.

NM_001145026 (versions 1 and 2) (NCBI RefSeq status: Reviewed)
[`NC_000012.11:g.80878310C>T`](https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chr12%3A80878305-80878315)
Both gene tracks map this variant to different versions of `NM_001145026:c.829C>T` / `p.(Gln277Ter)`, but positions 277 of the CDS of both NM_001145026.1 and NM_001145026.2 do not contain a Gln (Q), they contain a Thr (T).
Variant Validator maps this variant to `NM_001145026.1:c.1285C>T` / `p.(Gln429Ter)`, which does match the CDS.

NM_017848 (versions 4 and 6) (NCBI RefSeq status: Reviewed)
[`NC_000023.10:g.54209388T>G`](https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chrX%3A54209383-54209393)
Both gene tracks map this variant to different versions of `NM_017848:c.244A>C`, both resulting in `p.(Ile82Leu)`, but position 82 of the CDS of NM_017848.6 does not contain a Ile (I), but a Thr (T). The CDS of NM_017848.4 does contain an Ile there. This difference is not shown in the genome browser.

I argue that the aminoacids shown in the track should represent the true CDS of the given transcripts.

Thank you,
Ivo Fokkema
LOVD project

CC: @maximilianh, @AngieHinrichs (UCSC), @PeteCausey-Freeman (Variant Validator)

**Comment by AnnZweig** [comment]
Thanks for these suggestions, Ivo. I'm wondering if you would consider
sending them instead to the UCSC Genome Browser Help Desk at
genome@soe.ucsc.edu. At the help desk an entire team of folks will be able
to work together to provide the best answer. Note that all messages sent to
that address are archived on a publicly-accessible Google Groups forum. If
you'd rather it be a more private list, you may send it instead to
genome-www@soe.ucsc.edu.

**Comment by ifokkema** [comment]
OK, thank you, Ann! I was assuming this was a Dev choice and needed to be discussed here, but I'll take it up with the help desk, then! I'll refer to this issue in case they decide it's indeed something that needs to be fixed.

**Comment by braneyboo** [comment]
Thanks for writing our help desk, Ivo.  A ticket has been created and no doubt will result in a rousing internal discussion of what the right thing to do is.  =)

**Comment by ifokkema** [comment]
Thank you, Brian!
These transcripts are causing me headaches, I expect this will cause a few of you to experience the same :wink:

**Comment by AngieHinrichs** [comment]
Yes, this is a headache that has been cleared for our Variant Annotation Integrator but not (yet) for the exon numbers displayed in the Genome Browser.
