### ISSUE TITLE
Fasta sequence name validation

### ISSUE THREAD

**Issue by yunhailuo** [ucscGenomeBrowser/kent#41]
Dear UCSC,

Based on my reading (https://genome.ucsc.edu/FAQ/FAQformat.html#format18), it seems that fasta sequence name has no specific requirements. I'm wondering why validationFiles would like to restrict fasta sequence name with fastq standard: 

https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/encode3/validateFiles/validateFiles.c#L1136
https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/encode3/validateFiles/validateFiles.c#L455
https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/encode3/validateFiles/validateFiles.c#L258

This standard actually won't allow `|` which is used a lot by NCBI. Can this be updated?

**Comment by galt** [comment]
We were asked almost the same question, but this time about the letter "+".

Query about Kent utility validateFiles, fasta format
http://redmine.soe.ucsc.edu/issues/25132

The short answer is that this routine is NOT a general purpose fasta validator.
It was only intended to be used in the encode2 pipeline on a restricted set of fasta 
files that were generated directly from fastq files. They have a restricted set of chars
in the name, and only support acgt, not protein, and they cannot have multi-line sequence
files which are also an important part of the FASTA standard.

**Comment by yunhailuo** [comment]
> We were asked almost the same question, but this time about the letter "+".
> 
> Query about Kent utility validateFiles, fasta format
> http://redmine.soe.ucsc.edu/issues/25132
> 
> The short answer is that this routine is NOT a general purpose fasta validator.
> It was only intended to be used in the encode2 pipeline on a restricted set of fasta
> files that were generated directly from fastq files. They have a restricted set of chars
> in the name, and only support acgt, not protein, and they cannot have multi-line sequence
> files which are also an important part of the FASTA standard.

Thank you for the explain. To be clear, does that mean it won't be changed and we probably need our own validator?

**Comment by genome-www** [comment]
Hi Yunhailuo, I'm curious: can you give us a little bit of background about how you found our Encode fasta validator and for which project you want to use it? Are you working for a big DCC-like project at Stanford that needs a fasta validator or is this for a smaller lab-specific project for a publication? thanks!

**Comment by yunhailuo** [comment]
> Hi Yunhailuo, I'm curious: can you give us a little bit of background about how you found our Encode fasta validator and for which project you want to use it? Are you working for a big DCC-like project at Stanford that needs a fasta validator or is this for a smaller lab-specific project for a publication? thanks!

Hi, I worked at ENCODE-DCC. We currently using your tool for file validation. But we are getting more and more trouble with fasta and end up doing a lot of manual work. We want to check with you first to see how we can go forward.

**Comment by genome-www** [comment]
Ah so you're working right now for the ENCODE DCC? If so, could your
engineers modify the tool and remove some checks or add more checks that
you need? It may be only a change involving 3-4 lines of code...

>

**Comment by yunhailuo** [comment]
> Ah so you're working right now for the ENCODE DCC? If so, could your engineers modify the tool and remove some checks or add more checks that you need? It may be only a change involving 3-4 lines of code...
> […](#)

Sure. We will do that then.
