### ISSUE TITLE
Couldn't make directory ../trash/udcCache/

### ISSUE THREAD

**Issue by morganecf** [ucscGenomeBrowser/kent#45]
We have a LIMS plugin that redirects to the UCSC genome browser track view, and each time we trigger it, we get the error message below (path is truncated). This breaks the visualization.

```
Couldn't make directory ../trash/udcCache/https/storage.googleapis.com/broad-epi-tracks/track_026251.bwQ3FGoogleAccessIdQ3Dbroad-epiQ2540appspot.gserviceaccount.com
```

**Comment by braneyboo** [comment]
Hey @morganecf,

Could you include the whole path, or the URL that's generating this?   It looks like a problem with the code we use to generate directory names from URLs.

Thanks!

**Comment by morganecf** [comment]
Thanks for the quick reply! This is the url:  ```https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr19%3A11500000%2D12000000&hgsid=893586055_aZUdchF3aJtyjk2gjrAPyt2aeJut```

And this is the path: ```Couldn't make directory ../trash/udcCache/https/storage.googleapis.com/broad-epi-tracks/track_027938.bwQ3FGoogleAccessIdQ3Dbroad-epiQ2540appspot.gserviceaccount.comQ26ExpiresQ3D1602264182Q26SignatureQ3DB85wFCevSRnE8lwBsDWQ51AdsyQ51rQ51IZ4BnzauYhSPW4cdMStILO0Q252BnirG1HOmSAEamGYU0yEZxFazNCyIHMsrt2JBIUIWIpnVchuyuYoOq29XFOKHFpGMo2bGcPyODQ252FQ51GRMZZ1Da2CmXadEppgSEGmqMzvCsQ51ANWi4N0pTkzBQ513MviLbi5Yt93LQ252BQ51ooVYsNyQ252Fp33hZzKv6rOtKZqdjZA9UzFddZhurBVGNx32ROVmQ252F3jcetbjQ252FG34bIIaMRGPbBYE6JxPS19UPCeUBdDY2Hv4vtUefSNq0D3c35g0NQ252FCE7f9a6UsSEe7Y7UYqmRGl2YCPzS3kfhE3Q51E35Q252BAnPbVEsYmgQ253DQ253D```

**Comment by braneyboo** [comment]
Thanks @morganecf .   I can't reproduce this problem with that URL.  It looks like  your LIMS plug-in is generating that long string with broad-epi-tracks in it and somehow it's bypassing our code that automagically shortens these long names to SHA1 sequences.    Any chance you can capture that URL?

**Comment by morganecf** [comment]
This is the redirect url that we're automatically generating (our code hasn't changed for a while, and this was working before):

```https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&hgt.customText=https%3A%2F%2Fstorage.googleapis.com%2Fbroad-epi-trackview%2Fucsc%2Ff05093c7c2f78421d057f76a2a3051ee.txt%3FGoogleAccessId%3Dbroad-epi%2540appspot.gserviceaccount.com%26Expires%3D1602278731%26Signature%3DTTkB7%252FFbtjQq6VRl6xFS73kBKHM2qinX%252F5z0PSZWhR3KLVbCXEOLBky%252FdwCxgbyIrLUV4T9I4A9EPe283Gr%252FeZEwtVHoVEyITT4c%252B%252BjmAHaLNU0%252BG0hLR7o1we4oRoX0lvrJxTlZmM%252F1aHKXUwF4ybLx6uq0hVwFIO59wtLMsgvLJxdlc%252FVf4FPFRMSITDbbN25wZ1z3qc%252F6dFAMIILR%252F5NbZvKVEkGt5Ukk3z2IpjlWxvvrwsg91P8hlW6DeFrwl0jgU3mm9Nzc%252Fv1eD70Qjbpwy71GGfa0eA53ghKgv7XtJoK%252BWTnBbsZKK9OtpnX%252FtMvtLUQKL1GUbeAuNua0tQ%253D%253D&hgS_doLoadUrl=submit&hgS_loadUrlName=https%3A%2F%2Fbroad-epi.firebaseapp.com%2Ftrackview%2Fucsc%2Fsession.txt```

**Comment by braneyboo** [comment]
awesome.   I'll get back to you

**Comment by mohawkTrail** [comment]
Hi.  This is a signed URL, in case that's not obvious.  If it's skipping the shortening, perhaps that is the cause.

**Comment by braneyboo** [comment]
I fixed this on our development server.   Thanks for reporting it!  It was a bug in our code that I think was provoked by a change in Apache settings.   The fix will make it to our public server in two weeks.

**Comment by morganecf** [comment]
@braneyboo thanks so much!

**Comment by morganecf** [comment]
Hi @braneyboo, I see the fix (assuming it's this: https://github.com/ucscGenomeBrowser/kent/commit/7e6ba710dd2889aa522a4e6fd1f8a3ceb94e1055) has made it into your latest release. Does that mean it's out in production? When will we know when the fix is available on the public server? Thanks!

**Comment by braneyboo** [comment]
We push to the public site tomorrow afternoon.

**Comment by morganecf** [comment]
Awesome, thanks!
