### ISSUE TITLE
netClass query

### ISSUE THREAD

**Issue by lecook** [ucscGenomeBrowser/kent#48]
Hello,
I have a query about the netClass tool. 

```
netClass
Add classification info to net.
usage:
   netClass [options] in.net tDb qDb out.net
       tDb - database to fetch target repeat masker table information
       qDb - database to fetch query repeat masker table information
```
It's not clear what the format of the database files is. Do you have any further information on how to make these files (tDb and qDb) required to use this tool? 

Thanks!
Laura

**Comment by galt** [comment]
Please direct your question to the UCSC Genome Browser mailing list
 https://genome.ucsc.edu/FAQ/FAQmaillist.html#how1

**Comment by braneyboo** [comment]
Hey there Laura,

Sorry it took so long to get back to you.  We had a bit of a hiccup in our response protocol.   Here's what are mailing list person said:
---

Hello,

Thank you for using the UCSC Genome Browser and sending your inquiry.

The netClass utilitiy will not work unless you are running the tool in environments where there are genome browsers for every organism in the alignments. If you want to build nets without first creating these databases, then you will need to change this line in doBlastzChainNet.pl:

netClass -verbose=0 $tRepeats $qRepeats -noAr noClass.net $tDb $qDb $tDb.$qDb.net

to

mv noClassNet $tDb.$qDb.net

I hope this is helpful. If you have any further questions, please reply to genome@soe.ucsc.edu.
All messages sent to that address are archived on a publicly-accessible Google Groups forum.
If your question includes sensitive data, you may send it instead to genome-www@soe.ucsc.edu.

Jairo Navarro
UCSC Genome Browser

Want to share the Browser with colleagues?
Host a workshop: https://bit.ly/ucscTraining
