### ISSUE TITLE
bigWigAverageOverBed output sort order

### ISSUE THREAD

**Issue by gevro** [ucscGenomeBrowser/kent#49]
The output files are sorted by the bed item name column such that the order does not match the input bed file sort order. I believe this is a bug.

**Comment by braneyboo** [comment]
Hey @gevro, this is a speed optimization.  On large files the input is sorted by chromosome to make lookup more efficient.  I agree that the program probably should re-sort the output to be the same as the input, but I'm not sure when we'll get to this.  I opened a new internal ticket for this.  We'll get back to you if we fix this.

The way I'd get around this is by substituting names for the original names that will sort alphabetically to the same order as the input file.  Then you could sort the output of bigWigAverageOverBed to get back to the original order, perhaps restoring the original names after this step.
