### ISSUE TITLE
can't build Bio-BigFile

### ISSUE THREAD

**Issue by hkmztrk** [ucscGenomeBrowser/kent#51]
Hello,

I am trying to install Bio-BigFile-1.07 and consistently getting this  error after `./Build`

```
Building Bio-BigFile
cc -shared -O2 -L/usr/local/lib -fstack-protector -o blib/arch/auto/Bio/DB/BigFile/BigFile.so lib/Bio/DB/BigFile.o ~/kent/src/lib/x86_64/jkweb.a -lz -lssl
/usr/bin/ld: ~/kent/src/lib/x86_64/jkweb.a(bbiRead.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
~/kent/src/lib/x86_64/jkweb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error building blib/arch/auto/Bio/DB/BigFile/BigFile.so from lib/Bio/DB/BigFile.o at /software/perl/5.24.1/lib/5.20.2/ExtUtils/CBuilder/Base.pm line 323.
```

I updated the `CFLAGS=-fPIC` in  `kent/src/inc/common.mk` and run `make` in `kent/src/lib`
Also followed the below instructions: 
```
export MACHTYPE=x86_64
export PATH="~/bin/$MACHTYPE:$PATH
```

But nothing works. It'd be great if you can help me about this.

**Comment by maximilianh** [comment]
Hi @hkmztrk, after some googling I found that you're using a Gbrowse adaptor for bigWig files that uses the public domain part of our source code. Your approach of adding CFLAGS=-fPIC sounds good to me (I imagine you did a "make clean" after this?) but how Gbrowse integrates our code is outside our domain of expertise. It sounds like you should contact the Gbrowse adapter maintainers for some ideas https://github.com/GMOD/GBrowse-Adaptors/pull/19 I've CCed one of them here, but your problem should rather be handled in their issue tracker. We can also make small changes to makefile to make integrating our code easier @keiranmraine

**Comment by hkmztrk** [comment]
Thanks a lot for your fast response @maximilianh! Yes, I tried `make clean && make` afterwards but somehow it has no effect. Thanks for redirecting the issue.

**Comment by maximilianh** [comment]
I haven't redirected the issue, I just CC'ed someone over there. I don't
know how the other project works, so the best way forward would be if you
open a ticket over there.

**Comment by braneyboo** [comment]
Hey @hkmztrk,  what do you mean by "nothing works" or "somehow it has no effect".    Are you able to recompile the library with -fPIC ?

**Comment by hkmztrk** [comment]
Hi @braneyboo, 

After updating this line `CFLAGS` to `CFLAGS=-fPIC` in `kent/src/inc/common.mk`  I run `make clean && make` in `kent/src/lib`. make command works fine.  But when I go back to run `./Build` in Bio-BigFile-1.07 these changes have no effect and I receive the same error. 

I also tested what's suggested here: http://seqanswers.com/forums/archive/index.php/t-70219.html

run make in Kent folders with following:
`make CXXFLAGS=-fPIC CFLAGS=-fPIC CPPFLAGS=-fPIC`

After this I'm finally passed `./Build`  in Bio-BigFile-1.07  but this time `./Build test` fails,

```
Test Summary Report
-------------------
t/01.bigwig.t     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 29 tests but ran 0.
t/02.bigbed.t     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 15 tests but ran 0.
t/03.bigwig_high.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 32 tests but ran 0.
t/04.bigbed_high.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 35 tests but ran 0.
t/05.bigwig_set.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=5, Tests=0,  2 wallclock secs ( 0.07 usr  0.03 sys +  1.39 cusr  0.41 csys =  1.90 CPU)
Result: FAIL
Failed 5/5 test programs. 0/0 subtests failed.
```

I opened an issue here https://github.com/GMOD/GBrowse-Adaptors/issues/22

**Comment by braneyboo** [comment]
Yeah, this looks like something that they'll have to help you with.   I'm going to close this, but do get back to us if it looks like something going haywire with our code.

**Comment by hkmztrk** [comment]
One final question @braneyboo, @maximilianh: 

```
Make the directory ~/bin/$MACHTYPE which is
   where the (non-web) executables will go.
   Add this directory to your path to access the built binaries.
```

I realise that my ~/bin/$MACHTYPE (~/bin/x86_64) is empty. Does this mean I somehow failed compiling Kent?

**Comment by braneyboo** [comment]
From what you've said so far, @hkmztrk , it looks like you're only using the kent libraries.  If those were missing, your compile/link would have failed, so I don't think that's your problem.

I don't know anything about GBrowse, but this error message seems to imply that some configuration file is missing.

"Parse errors: Bad plan"
