### ISSUE TITLE
Install kent

### ISSUE THREAD

**Issue by linzhangTuesday** [ucscGenomeBrowser/kent#52]
Hi I am trying to install Kent to use on the server which I don't have root.

The binary I am trying to use is faSplit, faToTwoBit, TwoBitInfo et al.

Either downloading Kent as a whole or the binary, encountering the same error as below 

./faSplit: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by ./faSplit)
./faSplit: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./faSplit)
./faSplit: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./faSplit)

Thanks and please let me know if there is any suggestions.

**Comment by galt** [comment]
Precompiled Utilities  are here
http://hgdownload.soe.ucsc.edu/admin/exe/

Linux are here
http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/

Mac are here
http://hgdownload.soe.ucsc.edu/admin/exe/macOSX.x86_64/

**Comment by maximilianh** [comment]
Hi @linzhangTuesday, It looks like you have a very old version of GLIBC. Can you tell us which Linux version you are using and which distribution?

**Comment by linzhangTuesday** [comment]
Thanks for the follow up @maximilianh . Yeah, it is CentOS 6.10.

**Comment by linzhangTuesday** [comment]
it's solved. Thank you anyway!

**Comment by maximilianh** [comment]
Hi Linzhang, could you tell us or users who may stumble over this in the
future with web searches how you solved it?
