### ISSUE TITLE
No makefile in kent/src/lib

### ISSUE THREAD

**Issue by johnyaku** [ucscGenomeBrowser/kent#56]
Step 4 of the installation instructions fails because there is no makefile in kent/src/lib

**Comment by NullModel** [comment]
Good Evening John:  Can you clarify what type of view you have of the source tree where
it has no makefile in kent/src/lib/ ? --Hiram

**Comment by johnyaku** [comment]
Thanks Hiram.
I'm looking at src/lib on the master branch of this repo.

**Comment by genome-www** [comment]
How about this one?
https://github.com/ucscGenomeBrowser/kent/blob/master/src/lib/makefile

Also, can you tell us which "installation instructions" you're looking at?
We unfortunately have at least two different ones (and this ticket may help
us remove one of them)

**Comment by johnyaku** [comment]
My bad. Not sure how I missed that.
Turns out I messed up a COPY statement in my dockerfile, so the makefile didn't get copied across.
FYI, I have been following the instructions in the readme of the GitHub repo.

Sorry about the red herring, and thanks for your help!

**Comment by genome-www** [comment]
Thanks, we tend to forget about the update the top-level README. The
instructions there are correct, but could be shortened.
I imagine you're trying to setup a local mirror, in this case,
https://genome.ucsc.edu/goldenPath/help/mirror.html may be helpful.

**Comment by johnyaku** [comment]
Thanks for your reply and sorry about the slow response. Moved to a new role and have been snowed under since.

I was actually trying to containerise as many of your utilities as practical, so that they would be readily available to some colleagues that want to use them but have struggled to install them on our HPC without sudo rights.
There are some images on Docker Hub that include subsets of the kent utilities, but no complete sets.
I won't have time to complete this any time soon, but I thought I'd plant that seed of an idea. With a bit of careful planning, it should be possible to set up the docker build process so that it rebuilds a new version every time the codebase is updated.
