### ISSUE TITLE
compilation error with lib/uuid.c

### ISSUE THREAD

**Issue by lassancejm** [ucscGenomeBrowser/kent#6]
Hi, 

I am trying to re-compile the latest stable version, but am encountering the following error when making the libraries:

```
gcc -O -g  -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I../htslib -I/include -I/n/home01/lassance/include/libpng15  -o uuid.o -c uuid.c
In file included from uuid.c:9:0:
../inc/uuid.h:8:23: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
                       ^
compilation terminated.
make: *** [uuid.o] Error 1
```

I am using gcc version 4.8.2 & a Linux system (x86_64-redhat-linux-gnu).

Thanks!

**Comment by NullModel** [comment]
Good Morning:  You will need to install the libuuid-devel package
to obtain the /usr/include/uuid/ directory of files.  This appears
to be a new dependency with this recent addition of uuid code.

For example:

yum install libuuid-devel

--Hiram

**Comment by lassancejm** [comment]
Thanks for your answer.
