### ISSUE TITLE
Blat not finding Sequence

### ISSUE THREAD

**Issue by smoijueh** [ucscGenomeBrowser/kent#60]
The command line version of blat is not finding a sequence in the human genome. I'm able to locate that same sequence on the [UCSC Genome Browser](https://genome.ucsc.edu/cgi-bin/hgBlat) version of blat.
 
I downloaded the Linux command line version of [Blat](http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/blat/) (blat - Standalone BLAT v. 37x1 fast sequence search command line tool) and hg38.2bit from https://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/hg38.2bit. 

The specific sequence I want to query is 
>\>query1
GGTTTCGCAGATTTTTCCCGACTCTGTAATGTTGGCGGTGCAGGAAGGGATTGACTTACTCACTTTTCCGCCGGCGCCCGGTTCTCCGGAGCCGCCTCACCTTTCCCGGCAGCCCGAGCAGCCGGAGCAGAGAGCCTTGGGTCCGGTTTCTATGCCAAACCTTGTACCGGAGGTGATCGATCTTACCTGCCACGAGGCTTCCACCCAGTGACGACGAGGATGAAGAGGGTGAGGAGTTTGTGTTAGATTATGTGGAGCACCCCGGGCACGGTTGCAGGTCTTGTCATTATCACCGGAGGAATACGGGGGACCCAGATATTATGTGTTCGCTTTGCTATATGAGGACCTGTGGCATGTTTGTCTACA

Here's the blat command I'm using:
`./blat -noHead -out=psl ~/Downloads/hg38.2bit query.fa output.psl`

The command runs but nothing gets output to the `output.psl` file. The command works with other human genome sequences.

Here are the results from the BLAT UCSC genome browser:
![image](https://user-images.githubusercontent.com/42754056/134778400-4532a2df-a2ab-4f72-b890-6741876c2cc9.png)

It finds the sequence on the browser tool but not the command line version. I've tried hg38.2bit, hg19.2bit, and the whole genome fasta files for hg19 and hg38. Any suggestions on why the command line tool isn't finding this sequence?

**Comment by galt** [comment]
Please send your question to genome@soe.ucsc.edu mailing list. They have support for UCSC Genome Browser including BLAT questions.
