### ISSUE TITLE
Certificate validation (https.c) causing issues with build in v424

### ISSUE THREAD

**Issue by Stikus** [ucscGenomeBrowser/kent#64]
**Describe the bug**
After updating to the latest kent_base version (424) out build script failed with error. On 423 everything working (logs below).
```c
https.c: In function 'verify_callback':
https.c:322:47: error: dereferencing pointer to incomplete type 'X509_STORE_CTX {aka struct x509_store_ctx_st}'
     X509_NAME_oneline(X509_get_issuer_name(ctx->current_cert), buf, 256);
                                               ^~
At top level:
https.c:28:13: warning: 'openssl_locking_callback' defined but not used [-Wunused-function]
 static void openssl_locking_callback(int mode, int n, const char * file, int line)
             ^~~~~~~~~~~~~~~~~~~~~~~~
https.c:23:22: warning: 'openssl_id_callback' defined but not used [-Wunused-function]
 static unsigned long openssl_id_callback(void)
                      ^~~~~~~~~~~~~~~~~~~

```
 **To Reproduce**
```sh
docker run --rm -it ubuntu:18.04
apt update -yy && apt install -yy  wget build-essential libssl-dev
wget https://github.com/ucscGenomeBrowser/kent/archive/refs/tags/v424_base.tar.gz && tar -xzf v424_base.tar.gz && cd kent-424_base/src/lib/
cc -O -g "-fPIC" -std=c99 -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -DUSE_HIC   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I../htslib  -I/include -I/usr/include/libpng16  -o https.o -c https.c

```

 **Expected behavior**
```sh
wget https://github.com/ucscGenomeBrowser/kent/archive/refs/tags/v423_base.tar.gz && tar -xzf v423_base.tar.gz && cd kent-423_base/src/lib/
cc -O -g "-fPIC" -std=c99 -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -DUSE_HIC   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I../htslib  -I/include -I/usr/include/libpng16  -o https.o -c https.c

https.c:27:13: warning: 'openssl_locking_callback' defined but not used [-Wunused-function]
 static void openssl_locking_callback(int mode, int n, const char * file, int line)
             ^~~~~~~~~~~~~~~~~~~~~~~~
https.c:22:22: warning: 'openssl_id_callback' defined but not used [-Wunused-function]
 static unsigned long openssl_id_callback(void)
                      ^~~~~~~~~~~~~~~~~~~

```

 **Desktop (please complete the following information):**
  - OS: Ubuntu 18.04 docker container
```sh
# uname -a
Linux af8f990541cf 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

My attempt to find solution of this problem led me to these links: 

- issue https://github.com/openssl/openssl/issues/1730
- commit https://github.com/openssl/openssl/commit/ba6017a19346a169ca09bb67427ccf6fc56af0af
- and something similar https://github.com/hexchat/hexchat/issues/1759

Looks like `ctx->current_cert` should be changed.

Using `err_cert` as in commit gives me error:
```c
https2.c: In function 'verify_callback':
https2.c:323:44: error: 'err_cert' undeclared (first use in this function); did you mean 'errAbort'?
     X509_NAME_oneline(X509_get_issuer_name(err_cert), buf, 256);
                                            ^~~~~~~~
                                            errAbort
https2.c:323:44: note: each undeclared identifier is reported only once for each function it appears in

```
Using `errAbort` as suggested gives me warnings:
```c
https2.c: In function 'verify_callback':
https2.c:323:44: warning: passing argument 1 of 'X509_get_issuer_name' from incompatible pointer type [-Wincompatible-pointer-types]
     X509_NAME_oneline(X509_get_issuer_name(errAbort), buf, 256);
                                            ^~~~~~~~
In file included from /usr/include/openssl/ssl.h:20:0,
                 from https2.c:6:
/usr/include/openssl/x509.h:640:12: note: expected 'const X509 * {aka const struct x509_st *}' but argument is of type 'void (*)(char *)'
 X509_NAME *X509_get_issuer_name(const X509 *a);
            ^~~~~~~~~~~~~~~~~~~~

```

**Comment by NullModel** [comment]
Good Morning Grammatikati:

I would be curious to know if the pre-built binaries:

   http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/

function on the v424 system ?

**Comment by galt** [comment]
Hello, Grammatikati!
What version of openssl are you using?
You can get it from the command line like this:

command-line-prompt> openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by Stikus** [comment]
Ubuntu 18.04 have openssl 1.1.1 September 2018  iirk.

**Comment by galt** [comment]
I have fixed it in the source code on master branch.
Do a git pull and try again.

Alternatively, if using the beta release branch, that will be patched tomorrow.

**Comment by Stikus** [comment]
Thanks for quick fix, we'll use it when it comes to base release - I assume week or two.

Btw - any chance that you implement not only tags but GitHub releases too?

This option for notification don't see tags - only releases - that's why ppl like me should manually test for new release:
![image](https://user-images.githubusercontent.com/41360525/146143235-95a9a4e1-3a36-4a10-b97d-bffc107b9134.png)

**Comment by galt** [comment]
The beta branch has been updated with the fix.

**Comment by Stikus** [comment]
Closing issue due to fix, but will ask again about proper `release` feature, not only tags, @galt

**Comment by CarpeVida** [comment]
Hi @Stikus, 
We have not implemented the GitHub release feature, only tags. Thanks for the suggestion. It certainly would make sense. I made a note of your request and we will consider it, though I cannot say if or when it will be available.  
In any case, the v425 release occurred 1/18/22 and should include the fix Galt made. We normally operate on 3-week release cycles. 
Please let us know if you have any comments or questions and thank you for using the Genome Browser. We really do appreciate suggestions and detailed bug reports. 
Daniel Schmelter
UCSC Genome Browser
