### ISSUE TITLE
undefined reference 

### ISSUE THREAD

**Issue by suyanan** [ucscGenomeBrowser/kent#7]
According to your READ file, 
GENERAL INSTALL INSTRUCTIONS , the step 7, go to the directory **src/utils/fixCr** , then **make**:
but some errors about **undefined reference**(detailed in file named **error.txt**), how can I fix it ? OR I did something wrong?
[error.txt](https://github.com/ucscGenomeBrowser/kent/files/1318324/error.txt)

Finally , I wanna use the twoBitToFa utility to extract fasta from 2bit file, how about the difference of bioconda of ucsc-twobittofa ?
thank a lot.

**Comment by NullModel** [comment]
You can fetch all the pre-compiled user application binaries via rsync:

  rsync -azvP rsync://hgdownload.soe.ucsc.edu/genome/admin/exe/linux.x86_64/ ./

You will not need to build the binaries if these copies function on your system.

The error you display seems to indicate an obsolete file was used from
kent/src/inc/common.mk

If you do want to build the source tree you will need to update your source
tree.  Plus, check the updated kent/README instructions which have added
a missing step to build the libhts.a

The bioconda package you mention appears to package the twoBitToFa
binary into a docker package.  If that is kept up to date, that would be
a substitute for the command.

**Comment by suyanan** [comment]
Work done. I update the kent  from git , 
thanks your reminders and answers, so fast.
