### ISSUE TITLE
wigToBigWig doesn't work for chromosomes with spaces in name.

### ISSUE THREAD

**Issue by philippguevorguian** [ucscGenomeBrowser/kent#71]
**Describe the bug**
In using the wigToBigWig utility, an error is thrown if the name of the chromosome includes spaces or tabs.

**To Reproduce**
1. Download the attached test.zip files in which I've added a space to the chromosome name "chr22" to be "chr22 homo"
[test.zip](https://github.com/ucscGenomeBrowser/kent/files/10395580/test.zip)
2. unzip the downloaded file
3. Run `wigToBigWig test.wig test.sizes test_output.bw`
4. See error `invalid unsigned integer: "homo"`

**Expected behavior**
test_output.bw is created using test.wig data

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.5
- wigToBigWig version 2.9

**Additional context**
The source of the issue is the `bbiWrite.c` file in `kent/src/lib` which uses a hash to store the chromosome sizes, but only takes the 
first row of text from the .sizes file to get chromosome names and gets the second row to be the chromosome sizes, this doesn't 
adapt well to chromosome names with space. The reason this is important is that genome assemblies often have spaces in them by 
default, changing these names by text replacement is compute and time intensive and the spaces allow for more legible and 
detailed information regarding the chromosomes for better data provision. 

I would be happy to submit a pull request myself if necessary, although I am not a proficient in the C language, so it would take me some time to find an elegant solution that meets the high standard of code organization, legibility and efficiency in this repository. If someone could help me address this, or redirect me to an alternative channel of communication (or alternative approach), it would be much appreciated. Thank you!

**Comment by NullModel** [comment]
Good Evening:  I'm very curious about this request.  That would be an interesting challenge to support such names in these file formats where almost always space is the delimiter character between elements.  The usual practice when such multiple word names are desired in an identifier is to separate them by underscore _ character, or withCamelCase notation.   Some types of genomic annotation file formats are naturally tab separated elements which can allow for spaces in identifiers, but this is not a global definition.  Please note the definition of a sequence name format in the NCBI assembly submission guidelines: [https://www.ncbi.nlm.nih.gov/genbank/genomesubmit/#files](www.ncbi.nlm.nih.gov/genbank/genomesubmit/#files)

`Each sequence has a definition line beginning with a '>' and a unique identifier (SeqID), eg contig001, contig002. The SeqIDs must:

    Be <50 characters
    Can only include letters, digits, hyphens (-), underscores (_), periods (.), colons (:), asterisks (*), and number signs (#).
    Be unique within a genome
`

**Comment by philippguevorguian** [comment]
Thanks for your interest. I generally agree with and have no problems with the current standards for identifier nomenclature in principle. In practice however, spaces in identifiers are common, even when downloading genomes from NCBI. 

See here: https://www.ncbi.nlm.nih.gov/nuccore/NC_060925.1?report=fasta
Where the chromosome 1 name is: `NC_060925.1 Homo sapiens isolate CHM13 chromosome 1, alternate assembly T2T-CHM13v2.0`

I hope this explains the nature of my motivation for this change and why I think it would be valuable. As for the technical aspect of things, my understanding is that in `bbiWrite.c` file, the most flexible approach would involve parsing values from the end of the line backwards to a delimiter, and storing the remainder of the line (from start of the line to that delimiter) as the chromosome name. It seems to me this should be implemented in the `struct hash *bbiChromSizesFromFile(char *fileName)` block. Granted, a change might be necessary in parsing the wig file as well. 

Let me know what you think and thanks again!

**Comment by maximilianh** [comment]
Hi Phillip, thanks for your suggestion. Genomics is a field with a long history. Identifiers were defined by Genbank a long time ago, and the FASTA format was defined almost 40 years ago (wow!). Sequence identifiers cannot contain spaces by definition, see https://www.ncbi.nlm.nih.gov/genbank/fastaformat/. 

The identifer here is "NC_060925.1", the rest is just a human readable description, it's not the identifier. The splitting on space in bbiWrite is intentional, we do not support human readable descriptions in fields supposed to hold only identifiers in our binary formats and have no plan to change that in bigWig or bigBed formats, it would break a lot of old tools.

If you want human readable descriptions in your pipeline, you can either use underscores or - better - store the descriptions elsewhere (text file, sql database, etc) and show them when you display the identifiers to the user.
