### ISSUE TITLE
Proposal to remove S:417/440/505 in branch specific mask list.

### ISSUE THREAD

**Issue by aviczhl2** [ucscGenomeBrowser/kent#79]
[New research](https://www.biorxiv.org/content/10.1101/2023.05.01.538516v1.full.pdf) shows position S:417/440/505 reversion may offer great immune escape under current immune background of repeated omicron infections. Those reversions may produce real growth advantages and we may be expected to see variants having those mutations. 

Hence they shall be removed from branch-specific maskings of BA.2*, BA.2.75*, BA.5* and XBB* for better analysis. 

However, given that lots of artefacts are still existing and twisting the tree, it is better if a filter to distinguish between real reversions and dropouts on a certain position be added.

**Comment by maximilianh** [comment]
Angie says that you've been discussing this on slack, so closing
