### ISSUE TITLE
Bash reporting error

### ISSUE THREAD

**Issue by andrewdavidsmith** [ucscGenomeBrowser/kent#80]
https://github.com/ucscGenomeBrowser/kent/blob/551582f58256a4829f72f8ababc034e83c36b8fc/src/utils/userApps/fetchChromSizes#L31

I think the `==` syntax might not always work (maybe not POSIX) and when it does, it might depend on how `[[` and quotes are used. For me, despite the reported error, the script works on assemblies not referenced in this clause. Even for hg19 and hg38 it will produce chrom sizes, but seems not to apply the patch mentioned in that clause. Changing to this might work:
```
if [ "$DB" = "hg19" -o "$DB" = "hg38" ] ; then
``

**Comment by gerardoPerez1** [comment]
Hello, @andrewdavidsmith.

Thanks for submitting this bug report. You are correct, the == should be =. We have made this change to our script, and it will go out with our next software release on July 5th.
