### ISSUE TITLE
 undefined reference to sqlSetIsUcscMirror

### ISSUE THREAD

**Issue by RoelKluin** [ucscGenomeBrowser/kent#81]
After 5fad625 compilation fails with undefined reference to sqlSetIsUcscMirror, adding a function in `hg/lib/hdb.c` resolves this:
```
static void sqlSetIsUcscMirror(boolean b) {}
```
Possibly you run only into this when running `make`, instead of `make utils`, the rest went fine thereafter.

**Comment by maximilianh** [comment]
Oops, sorry, I missed a file. Reverted the commit for now (may take a few minutes to arrive on Github). Thanks for letting us know!
