### ISSUE TITLE
errors reported by axtchain

### ISSUE THREAD

**Issue by yeeus** [ucscGenomeBrowser/kent#85]
**Describe the bug**
```
NC_000005.10:110000000-120000000 is not in /path/to/GRCh38_noY.2bit
```

 **To Reproduce**
 I followed the instruction on the website http://genomewiki.ucsc.edu/index.php/Same_species_lift_over_construction to liftover the annotations on GRCh38 to my genome assembly. This error was produced to by `axtchain` in the Step 2 - chain/net.

 **Expected behavior**
 Finally get the chain file.

Best wishes!

**Comment by christopherLee1** [comment]
What are the chromosome names /path/to/GRCh38_noY.2bit? Something like this command will list the chromosomes:
twoBitInfo /path/to/GRCh38_noY.2bit stdout

Also where did you get this 2bit file from? From our download server?

**Comment by yeeus** [comment]
I downloaded GRCh38 genome from NCBI and maybe axtchain read the record name rather than id like faTotwoBit..
I have solved this problem, thanks for your answer.
