### ISSUE TITLE
Correct Citation to Use

### ISSUE THREAD

**Issue by nathanhaigh** [ucscGenomeBrowser/kent#9]
I have used these tools and would like to cite them. Can you provide info on the correct citation to use?

**Comment by christopherLee1** [comment]
Hi Nathan,

Please see our citation page:
http://genome.ucsc.edu/cite.html

If the tools you've used do not fall under the specifically listed tools, then please cite our most recent Browser update publication:
https://academic.oup.com/nar/article-lookup/doi/10.1093/nar/gkx1020

If you have further questions, feel free to send an email to one of our mailing lists:
genome@soe.ucsc.edu - Public mailing list for general questions
genome-www@soe.ucsc.edu - Private mailing list for questions regarding private data
genome-mirror@soe.ucsc.edu - Public mailing list for mirror related questions

Christopher Lee
UCSC Genomics Institute
