### ISSUE TITLE
Request for Assistance with kent-tools Version 438 in Conda Repository

### ISSUE THREAD

**Issue by yhw320** [ucscGenomeBrowser/kent#91]
Hi,
I am writing to seek your assistance regarding the kent-tools package that your team has submitted to the Conda repository. I have encountered an issue while using this tool, and I would greatly appreciate your help in resolving it.

Our team has developed a software package, which internally relies on the kent-tools version 438. However, it seems that version 438 is no longer available in the Conda repository, with only version 472 currently being hosted (https://anaconda.org/dnachun/kent-tools/files). This situation has caused the installation of our package to fail, as it cannot locate the required kent-tools version 438.

Therefore, I kindly request that your team consider restoring the kent-tools version 438 in the Conda repository. This would greatly facilitate the installation and use of our  software.

Thank you very much for your time and support. I look forward to your positive response and appreciate any assistance you can provide in this matter.

**Comment by maximilianh** [comment]
Hi Hongwei, 

we do not manage the conda package. The link that you sent us indicates directly that Daniel Nachun manages this package: https://anaconda.org/dnachun You'd have to contact him for details on these conda packages.

We make changes every three weeks and most of our hundreds of tools change very little, we try to stay as backwards compatible as possible and usually add more tools, not modify old ones. If you pipeline was run with 438, and we're now at 472, it's very very likely that your pipeline will still give the same results. 

Which tools are you using in your pipeline? We can comment on specific tools if needed.

Hope this helps and let us know if the new version works for you,
best
Max

**Comment by yhw320** [comment]
Hi Max,
thank you very much for your prompt response! 

Actually, I was uploading my software to the conda repository, and version 438 of the kent-tools software was packaged as a dependency within our software. However, users are now encountering an error when downloading our software because version 438 of kent-tools is no longer available in the Conda repository. 
![微信图片_20241107101642](https://github.com/user-attachments/assets/07328bd6-4ffc-4219-98c7-fb330e796132)

In that case, I will try to reach out to Daniel Nachun again to see if he has any good solutions. 

Thank you once again for your reply.

**Comment by genome-www** [comment]
Hi Hongwei, I'm curious what Daniel suggested?

And still interested which parts of our kent tree you use in your pipeline.

I'd suggest not to depend on a specific version of our tools but to assume
that we won't change them. I know that doesn't sound ideal, but with a
three week release cycle and the system of binary distribution used by the
conda packages, I doubt that conda can store all past versions of all
tools. We make very few changes to the tools, our main job is to work on
our website and you're not using the code of the website.
